root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp\\main.exe ."
bin = "tmp\\main.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp", "logs"]
delay = 1000 # 檔案變更後延遲 1000ms 重新編譯
stop_on_error = true

[log]
time = true # 在日誌中顯示時間戳

[misc]
clean_on_exit = true # 退出時清理臨時檔案